name: 'Tagging Module Repos'
run-name: "Running workflow to update tags on Module Repository - ${{ github.event.inputs.repo_name }}"
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the repository'
        required: true
        type: string
      version_tag:
        description: 'Tag value'
        required: true
        type: string
      suffix:
        description: 'suffix'
        required: true
        type: choice
        options:
          - rc
          - ga
       
env: 
  ORG_NAME: 'vikas-awspro'
  REPO_NAME: ${{ github.event.inputs.repo_name }}
  CODE_TAG: ${{ github.event.inputs.version_tag }}
  CODE_SUFFIX: ${{ github.event.inputs.suffix }}

permissions: 
  contents: write

jobs:
  release_tag:
    name: Tag Modules Repo
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_NAME }}
          ref: ${{ env.CODE_TAG }}
          token: ${{ secrets.REMOTE_GITHUB_ACTION }}
      
      - name: Create and push new tag
        #env:
         # GITHUB_TOKEN: ${{ secrets.REMOTE_GITHUB_ACTION }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ env.CODE_TAG }}-${{ env.CODE_SUFFIX }}" -m "Release - ${{ env.CODE_TAG }}-${{ env.CODE_SUFFIX }}"
          git push origin "${{ env.CODE_TAG }}-${{ env.CODE_SUFFIX }}"
          

 
