name: 'Tagging Module Repos'
run-name: "Running workflow to update tags on Module Repository - ${{ github.event.inputs.repo_name }}"
on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the repository'
        required: true
        type: string
        default: 'vikas-awspro/aapkavikas-modules'
      version_tag:
        description: 'Tag value'
        required: true
        type: string
        default: 'v0.1.0'
      suffix:
        description: 'suffix'
        required: true
        type: choice
        options:
          - rc
          - ga
        default: 'rc'
        

permissions: 
  contents: write

jobs:
  release_tag:
    name: Tag Modules Repo
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_name }}
          ref: ${{ github.event.inputs.version_tag }}
          token: ${{ secrets.REMOTE_GITHUB_ACTION }}
      
      - name: Create and push new tag
        #env:
         # GITHUB_TOKEN: ${{ secrets.REMOTE_GITHUB_ACTION }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "${{ github.event.inputs.version_tag }}-${{ github.event.inputs.suffix }}" -m "Release - ${{ github.event.inputs.version_tag }}-${{ github.event.inputs.suffix }}"
          git push origin "${{ github.event.inputs.version_tag }}-${{ github.event.inputs.suffix }}"
          

 
